### ISSUE TITLE
xamarin forms build error 1.52.0

### ISSUE THREAD

**Issue by julesx** [Fody/PropertyChanged#204] opened 2016-10-12 15:21 UTC
```
2>MSBUILD : error : Fody: An unhandled exception occurred:
2>MSBUILD : error : Exception:
2>MSBUILD : error : Object reference not set to an instance of an object.
2>MSBUILD : error : StackTrace:
2>MSBUILD : error :    at EqualityCheckWeaver.InjectEqualityCheck(Instruction targetInstruction, TypeReference targetType) in C:\projects\propertychanged\PropertyChanged.Fody\EqualityCheckWeaver.cs:line 92
2>MSBUILD : error :    at EqualityCheckWeaver.CheckAgainstField() in C:\projects\propertychanged\PropertyChanged.Fody\EqualityCheckWeaver.cs:line 39
2>MSBUILD : error :    at EqualityCheckWeaver.Execute() in C:\projects\propertychanged\PropertyChanged.Fody\EqualityCheckWeaver.cs:line 32
2>MSBUILD : error :    at ModuleWeaver.ProcessTypes(List`1 notifyNodes) in C:\projects\propertychanged\PropertyChanged.Fody\TypeProcessor.cs:line 38
2>MSBUILD : error :    at ModuleWeaver.ProcessTypes(List`1 notifyNodes) in C:\projects\propertychanged\PropertyChanged.Fody\TypeProcessor.cs:line 45
2>MSBUILD : error :    at ModuleWeaver.Execute() in C:\projects\propertychanged\PropertyChanged.Fody\ModuleWeaver.cs:line 43
2>MSBUILD : error :    at lambda_method(Closure , Object )
2>MSBUILD : error :    at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 161
2>MSBUILD : error :    at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 82
2>MSBUILD : error : Source:
2>MSBUILD : error : PropertyChanged.Fody
2>MSBUILD : error : TargetSite:
2>MSBUILD : error : Void InjectEqualityCheck(Mono.Cecil.Cil.Instruction, Mono.Cecil.TypeReference)
2>MSBUILD : error : 
```

doesn't happen when i revert to earlier version 1.51.3

**Comment by renzska** [comment] 2016-10-14 15:25
I am also getting this same error. I don't get this error with 1.51.3, but when I update to 1.52.0, I get the error. It looks like there were changes in the this function in the latest 1.52.0 commit. For now, I've reverted back to 1.51.3.

Thanks for all your hard work!

**Comment by distantcam** [comment] 2016-10-14 15:31
Same as #200 should be fixed soon

**Comment by SimonCropp** [comment] 2017-04-23 14:05
can u try 1.53

**Comment by xi-guan** [comment] 2017-04-26 14:10
Have verified 1.53. It doesn't work. Have to revert back to 1.51.3

**Comment by SimonCropp** [comment] 2017-05-26 02:17
given i dont have xamarin does anyone on this thread want to attempt a PR to fix this issue?

**Comment by SimonCropp** [comment] 2017-05-26 02:34
or can someone at least re-test and give us a new stack trace?

**Comment by calvin-fisher** [comment] 2017-06-11 16:41
Confirmed works using latest Xamarin.Forms (2.3.4.247)

Getting it to work is less transparent than in older versions of PropertyChanged, but there are no build errors.

If anyone else is having trouble, note that the Page class implements property changed way down the inheritance chain, so the new opt-out mechanism will ignore it.  You have to create a dedicated viewmodel class for your bindings.

**Comment by SimonCropp** [comment] 2017-06-12 00:21
Sorry not sure what u mean by less transparent?

And deep hierarchy should not matter. If it doesnt find it then it is a bug

**Comment by calvin-fisher** [comment] 2017-06-12 13:39
By less transparent, I mean I think that the deprecated [ImplementPropertyChanged] attribute more clearly communicated in the code when and where weaving was taking place.

I think it's working as intended, though?  But it's possible I'm just not understanding what's intended.  Or maybe it is a bug.

A base-base-base-base-base-base class of Xamarin.Forms.Pages already explicitly implements INotifyPropertyChanged:
```
public abstract class BindableObject : INotifyPropertyChanged, IDynamicResourceHandler
{
    // ...
    public event PropertyChangedEventHandler PropertyChanged;
    // ...
}
```
So if try to bind Xamarin.Forms UI elements to properties on a Xamarin.Forms.Page, the implementation is not being weaved in for its properties and the UI does not get updated as I expected:
```
public class TestPage : ContentPage, INotifyPropertyChanged
{
    public TestPage()
    {
        TestText = "Loading...";
        BindingContext = this;
        InitializeComponent(); // UI sets up binding to TestText here
        TestText = "This does not show up on the UI :(";
    }
    public string TestText {get; set; }
}
```

If I create a separate class with the "Add..." attribute and bind to properties on that, it works fine.
```
[AddINotifyPropertyChangedInterface]
public class TestViewModel
{
    public string TestText {get; set; }
}
public class TestPage : ContentPage
{
    public TestPage()
    {
        var viewModel = new TestViewModel { TestText = "Loading..." };
        BindingContext = viewModel;
        InitializeComponent(); // UI sets up binding to TestText here
        TestText = "This shows up on the UI :)";
    }
}
```

**Comment by julesx** [comment] 2017-06-12 18:51
that's because only the base class will have any weaving implemented.

in your example, TestPage does not inherit from it's base, you are thinking of it backwards.

If TestPage implemented something, ContentPage would too.  Not the other way around.

**Comment by SimonCropp** [comment] 2017-09-25 01:44
Given the original bug seems to be fixed i am closing this

**Closed by SimonCropp** 2017-09-25 01:44 UTC
