### ISSUE TITLE
Adding PropertyChange.Fody to WPF project results in various native memory issues

### ISSUE THREAD

**Issue by timbilt** [Fody/PropertyChanged#655] opened 2020-10-07 23:21 UTC
First of all please pardon me if this format is a little bit off --- I am trying to stick to the format and provide as much info as possible.

I am using Visual Studio 2019 (MSBUILD 16.0) and have a solution that has a few projects. 

2 Core base projects: .NET standard 2.0
All other projects: .NET Framework 4.7.2

Some of the base projects control hardware devices via SDKs

Base classes that implement INotifyPropertyChanged exist in both .NET Standard 2.0 projects.

Intermediate base classes exist in a .NET Framework 4.7.2 project

All concrete implementations are in the main WPF project which is .NET Framework 4.7.2

1. Install PropertyChanged.Fody via NuGet package manager ONLY in the WPF main project
2. (Optional) Add [assembly: PropertyChanged.FilterType("My.Specific.OptIn.Namespace.")] to disable injection
3. Start application
4. Calls to 3rd party library that uses native memory start to fail with random memory errors consistently.

Due to the nature of the hardware projects that are failing, it's hard to reproduce in a sample app.  Does this have something to do with the fact that 2 base projects are .NET Standard 2.0? Do I have to use specific versions of PropertyChanged.Fody in each project?

**Comment by SimonCropp** [comment] 2020-10-08 00:16
can u re read the issue template and take all the required steps https://github.com/Fody/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by timbilt** [comment] 2020-10-08 01:00
> can u re read the issue template and take all the required steps https://github.com/Fody/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

Sorry. Updated --- trying to do the best format. What's annoying is that even if I essentially disable the weaver via the filter attribute by specifying only a non-existing namespace, the hardware projects still throw exceptions.

**Comment by SimonCropp** [comment] 2020-10-08 02:32
can you share a minimal stand alone solution that reproduces this issue?

**Comment by timbilt** [comment] 2020-10-08 02:50
I will try. But in the mean time can I at least get a suggestion?

**Comment by BrunoJuchli** [comment] 2020-10-08 18:14
Suggestion: compare the IL of your assembly when PropertyChanged.Fody is enabled and when it's disabled.

**Comment by timbilt** [comment] 2020-10-08 20:11
Taking a look with a memory profiler, I found something very interesting. When the process builds normally without PropertyChanged.Fody, the maximum addressable memory is 4GB, however with PropertyChanged.Fody it is 2GB.  The application btw is compiled with ANYCPU + Prefer32 bit which I think adds the /LARGEADDRESSAWARE build flag by default.

**Comment by timbilt** [comment] 2020-10-09 14:56
I have confirmed that PropertyChanged.Fody does in fact affect the flags that the application get's compiled with.

**Before (ANYCPU + Prefer 32)**
![Plain Build](https://user-images.githubusercontent.com/6863988/95597763-0c341000-0a1d-11eb-9ea1-aa90657f13b7.png)

**After (with Fody)**
![Weaved Build](https://user-images.githubusercontent.com/6863988/95597842-28d04800-0a1d-11eb-836e-5b84b14faa62.png)

My workaround was to install the [LargeAddressAware NuGet package](https://github.com/KirillOsenkov/LargeAddressAware) and add the following properties to my .csproj
`<PropertyGroup>
    <LargeAddressAware>true</LargeAddressAware>
    <LargeAddressAwareAfterTargets>FodyTarget</LargeAddressAwareAfterTargets>
  </PropertyGroup>`
The target from this Nuget Package only runs if you set your Platform Target to x86 in your project properties.

It would however be nice if Fody would not have led to this unexpected change to begin with.  Please fix.

**Comment by SimonCropp** [comment] 2020-10-09 23:13
@timbilt this looks like a bug in cecil. can u raise an issue here https://github.com/jbevain/cecil

**Comment by SimonCropp** [comment] 2020-10-10 00:15
@jbevain fyi

**Comment by tom-englert** [comment] 2020-10-11 08:30
Looks like this is already reported: https://github.com/jbevain/cecil/issues/620

**Comment by SimonCropp** [comment] 2020-10-12 08:43
ok given this is tracked upstream, i will close this

**Closed by SimonCropp** 2020-10-12 08:43 UTC
