### ISSUE TITLE
Strange issue with Bindingsource.CurrentItemChanged

### ISSUE THREAD

**Issue by Tiku123** [Fody/PropertyChanged#115] opened 2015-03-03 04:52 UTC
Hello ! 
I have a situation when your tool is causing a strange behavior. I'm using entity framework 6.1. I have a Bindingsource that has as datasource an entity. On my form I have a DataGridView bound to this Bindingsource.

I use the event BindingSource.CurrentItemChanged to make some actions when the data is changed.

Until now I have implemented the Property changed using my code :

Partial Public Class My_item Implements INotifyPropertyChanged
Private privatecmh As Decimal
Public Property cmh() As Decimal
    Get
        Return privatcmh
    End Get
    Set(ByVal value As Decimal)
        privatcmh = value
        OnPropertyChanged(&quot;cmh&quot;)
    End Set
End Property

.......// the same code for other properties //

Public Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged
Private Sub OnPropertyChanged(ByVal prn As String)
    RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(prn))
End Sub

End Class

Everything was working ok. When the user change some data on datagridview , the event BindingSource.CurrentItemChanged is fired and everything is ok.

I try to use your tool. But the problem is that I have a strange behavior. If I just click an item on datagridview without changing anything , and after click on another control , the event BindingSource.CurrentItemChanged is fired.

What can I do ?
 Thank you !

**Comment by SimonCropp** [comment] 2015-03-03 05:20
Please upload a solution that reproduces this problem

**Comment by Tiku123** [comment] 2015-03-03 05:54
this is not possible because is a very big project with a large database. But at least what is different the code on your tool compared with my code that is working.

**Comment by distantcam** [comment] 2015-03-03 06:32
In your property setter you're calling `OnPropertyChanged` without checking if the property has actually changed.

This code is supposed to be added by `PropertyChanged.Fody` but you're adding it manually, so `PropertyChanged.Fody` I believe won't modify the code. (Is that correct @SimonCropp?)

Instead, just have the setter set the internal variable.

**Comment by SimonCropp** [comment] 2015-03-03 07:15
> This code is supposed to be added by PropertyChanged.Fody but you're adding it manually, so PropertyChanged.Fody I believe won't modify the code.

yes that is correct.

@Tiku123 

> this is not possible because is a very big project with a large database.

Create a new solution with only the moving pieces that represent your problem

**Comment by Tiku123** [comment] 2015-03-03 17:41
@distantcam 
Maybe it's a little misunderstanding.
When I use only my code ( without fody ) , everything works ok.
If I delete my code , and install fody to do this job , I have this problem.

**Comment by SimonCropp** [comment] 2015-03-03 22:28
@Tiku123 unless you can provide a repro it will be very difficult to work out the cause of your problem.  So if u cant spend the time to create that repro i suggest you stop using fody until you can dedicate the time

**Comment by SimonCropp** [comment] 2015-03-08 06:21
closing this for now. feel free to raise a new issue when you can provide a repro

**Closed by SimonCropp** 2015-03-08 06:21 UTC
