### ISSUE TITLE
Can't install PropertyChanged.Fody.2.0.1

### ISSUE THREAD

**Issue by VahidN** [Fody/PropertyChanged#245] opened 2017-05-27 08:45 UTC
```
PM> install-package PropertyChanged.Fody

Attempting to gather dependency information for package 'PropertyChanged.Fody.2.0.1' with respect to project 'DomainClasses', targeting '.NETFramework,Version=v4.5'
Gathering dependency information took 780.03 ms
Attempting to resolve dependencies for package 'PropertyChanged.Fody.2.0.1' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'PropertyChanged.Fody.2.0.1'
Resolved actions to install package 'PropertyChanged.Fody.2.0.1'
Retrieving package 'Fody 2.0.0' from 'Package source v3'.
Retrieving package 'PropertyChanged.Fody 2.0.1' from 'Package source v3'.
Adding package 'Fody.2.0.0' to folder 'D:\Prog\packages'
Added package 'Fody.2.0.0' to folder 'D:\Prog\packages'
Added package 'Fody.2.0.0' to 'packages.config'
Executing script file 'D:\Prog\packages\Fody.2.0.0\tools\install.ps1'
Successfully installed 'Fody 2.0.0' to DomainClasses
Install failed. Rolling back...
Package 'PropertyChanged.Fody.2.0.1 : Fody [2.0.0, 3.0.0)' does not exist in project 'DomainClasses'
Removed package 'Fody.2.0.0' from 'packages.config'
Package 'PropertyChanged.Fody.2.0.1 : Fody [2.0.0, 3.0.0)' does not exist in folder 'D:\Prog\packages'
Removing package 'Fody.2.0.0' from folder 'D:\Prog\packages'
Access to the path 'D:\Prog\packages\Fody.2.0.0\Fody.dll' is denied.
Access to the path 'Fody.dll' is denied.
Removed package 'Fody.2.0.0' from folder 'D:\Prog\packages'
Executing nuget actions took 7.29 sec
install-package : Could not install package 'PropertyChanged.Fody 2.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the p
ackage does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ install-package PropertyChanged.Fody
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:11.2495730
One or more packages could not be completely uninstalled: 'D:\Prog\packages\Fody.2.0.0'. Restart Visual Studio to finish uninstall.
```
It looks for the Fody [2.0.0, 3.0.0) and even it's there, it tries to uninstall it. If I install the latest Fody separately, the same process happens again.

**Comment by SimonCropp** [comment] 2017-05-27 08:46
duplicate of https://github.com/Fody/PropertyChanged/issues/243

**Closed by SimonCropp** 2017-05-27 08:46 UTC

**Comment by VahidN** [comment] 2017-05-27 21:22
The `.nuspec` file doesn't contain the appropriate targetFramework:
```xml
<group targetFramework=".NETStandard1.3">
  <!--<dependency id="System.Reflection" version="4.3.0" exclude="Build,Analyzers" />-->
  <!--...-->
</group>
```
If it had one, I knew it requires .NET 4.5.1, .net standard 2.0 requires .NET 4.6.

**Comment by SimonCropp** [comment] 2017-05-28 02:21
Sorry i don't understand. The attribute assembly has no dependencies. Are u getting some build error? What .net version r u trying to target?

**Comment by VahidN** [comment] 2017-05-28 05:03
Actually the `PropertyChanged.dll` file has this attribute
```csharp
[assembly: TargetFramework(".NETStandard,Version=v1.3", FrameworkDisplayName = "")]
```
And when you create a NuGet package with the newer dotnet cli toolset, you will get the mentioned `group targetFramework=` in the produced `.nuspec` file and it will be shown in the NuGet site to guide users.
Plus it's possible to have multiple `targetFramework`'s in one nuget package, without forcing users to use a specific targetFramework. You should not limit users to `.NETStandard,Version=v1.3` only.

**Comment by SimonCropp** [comment] 2017-05-29 03:16
can u try 2.1. if that doesnt work please upload a sample solution that you are trying to target
