### ISSUE TITLE
Bring back ImplementPropertyChangedAttribute

### ISSUE THREAD

**Issue by virzak** [Fody/PropertyChanged#247] opened 2017-05-29 02:43 UTC
ImplementPropertyChangedAttribute is all over my big project. Besides, now there is a warning "The event '<ClassName>.PropertyChanged' is never used". Can you provide a clearer explanation as to why this breaking change is necessary? A lot of applications are affected I assume.

Can you bring this attribute back?

**Comment by SimonCropp** [comment] 2017-05-29 02:49
i removed it because too many people were using it without reading the doco, then when it did not work as expected, raising bugs or abusing me https://github.com/Fody/PropertyChanged/issues/183#issuecomment-304241436

see my response here https://github.com/Fody/PropertyChanged/issues/183#issuecomment-304419967

TBH i dont know what to do here.

**Comment by SimonCropp** [comment] 2017-05-29 02:51
i am wondering if i should add it back as a hidden feature, that people can only discover by reading the doco

**Comment by distantcam** [comment] 2017-05-29 02:52
@virzak Can you introduce a base class that implements `INotifyPropertyChanged` and then have all the other classes use that?

@SimonCropp That sounds like a @petersgiles suggestion.

**Comment by SimonCropp** [comment] 2017-05-29 02:54
@distantcam yeah i know. TBH personally i am not a fan of base classes for this type of functionality

@virzak perhaps just suppress "The event '.PropertyChanged' is never used"?

**Comment by distantcam** [comment] 2017-05-29 02:55
> TBH personally i am not a fan of base classes for this type of functionality

Yeah I understand. I hear Java supports multiple inheritance.

**Comment by virzak** [comment] 2017-05-29 02:56
@SimonCropp still reading that thread, but I would suggest that those who were using the attribute properly should not be penalized because of improper use by others.

**Comment by SimonCropp** [comment] 2017-05-29 02:57
> I hear Java supports multiple inheritance.

the troll is strong in this one

**Comment by SimonCropp** [comment] 2017-05-29 02:59
>  but I would suggest that those who were using the attribute properly should not be penalized because of improper use by others.

@virzak i agree. but it leaves me in an uncomfortable situation. 

people use it wrong and raise an issue. I engage and give them a detailed response and it waste my time. or i dont engage and give them succinct response and i get abuse

**Comment by SimonCropp** [comment] 2017-05-29 02:59
@virzak but u didnt answer. perhaps just suppress "The event '.PropertyChanged' is never used"?

**Comment by distantcam** [comment] 2017-05-29 03:01
What about a marker interface instead of an attribute? Then PropertyChanged implements `INotifyPropertyChanged` in place of that interface? It implies that all subclasses inherit the interface, which was the misunderstanding about the attribute.

    public class SomeViewModel: IImplementPropertyChanged

**Comment by virzak** [comment] 2017-05-29 03:02
@SimonCropp It does work, but that means: implementing an interface + 3 lines of code. 2 for warning + 1 for event.

Kinda defeats the purpose of the functionality, since it was way cleaner before.

**Comment by SimonCropp** [comment] 2017-05-29 03:03
@distantcam i still foresee people using that interface as perceived way of opting in to property notification

**Comment by distantcam** [comment] 2017-05-29 03:05
Isn't that ok though? So long as they understand that all subclasses are also opting in. I haven't seen all the problems you have about that attribute.

**Comment by SimonCropp** [comment] 2017-05-29 03:07
@distantcam the problem is people see the marker attribute, and i suspect the maker interface, and think "oh that is how i opt in to choose to inject OnPropChanged to property sets". And by inference "if i omit the marker than OnPropChanged will not be injected into property sets"

**Comment by distantcam** [comment] 2017-05-29 03:09
Yeah, and I suddenly realised you'll get issues opened like "How do I not implement `IImplementPropertyChanged` on a subclass?"

**Comment by virzak** [comment] 2017-05-29 03:41
@SimonCropp I read the comments. Maybe an FAQ should be created to address all these concerns. But I didn't see anything in the comments where anyone specifically asked for the ImplementPropertyChanged to be deprecated.

I imagine that by the time people come to work on Monday and decide to upgrade the library, all hell will break loose. There are probably 100 people that are using the library properly for 1 person who doesn't get it.

I love the library, and it is mind boggling how there could be any confusion about what the attribute does. It is literally the easiest thing to understand.

Breaking changes like this one should at the very least have IsError = false for a few releases, but yeah... please bring it back ASAP and don't penalize those who used it correctly.

**Comment by zspitz** [comment] 2017-05-29 07:35
@SimonCropp Firstly, I don't know if you hear this enough, but Fody.PropertyChanged specifically and Fody in general are both tremendous time-savers and brilliant ideas. Thank you so much for this.

> I engage and give them a detailed response and it waste my time. or i dont engage and give them succinct response and i get abuse

I understand that this issue comes up again and again. If you have a FAQ with the answers to these questions (_Why do all my classes have woven properties?_, _Are there any plans to make Fody.PropertyChanged opt-in per-class?_ etc.), then you can simply answer with a canned "_Please read the FAQ._" and a link. 

An alternative might be to separate this functionalityof [ImplementPropertyChanged] into a separate Fody plugin. This might help clarify that Fody,PropertyChanged does the property weaving for all INPCs in the project.

I want to reiterate how appreciative I am of all your work here, and hopefully provide some counterbalance to the naysayers.

**Comment by buzzware** [comment] 2017-05-29 10:51
I second the value of humble little project. Coming from Ruby, EmberJs and Adobe Flex, I can't believe that I would be expected to explicitly implement every property in order to get binding, as is the case in .Net. So for me this project alone makes my models look like they should. I'm not aware of any alternative project.

However, I also misunderstood the meaning of the attribute, and I can't understand why any library would do magic on all classes in a project with something as common as INotifyPropertyChanged. It should be opt in, and thats what so many thought it was doing, so why not just make it do what we thought it was doing?

**Comment by buzzware** [comment] 2017-05-29 10:58
Also, the reason I upgraded and found this, was that with Xamarin we are crossing over to MSBuild and .Net Standard, and something with an older verson of this project. After upgrading, I have this additional breaking change to contend with. I'm not sure how to go forward (yet), and I can't stay in the old world forever.

**Comment by SimonCropp** [comment] 2017-05-29 10:59
@buzzware 

>  It should be opt in, and thats what so many thought it was doing, so why not just make it do what we thought it was doing

you answered own question

>  I can't believe that I would be expected to explicitly implement every property in order to get binding, 

The aim of this project is "what if the only thing i needed to get property notifications was to have INotifyPropertyChanged".

**Comment by SimonCropp** [comment] 2017-05-29 11:08
so if we were to bring this back, can we come up with a better name that does not invite confusion?

perhaps `[AddINotifyPropertyChangedIngerface]`?

**Comment by virzak** [comment] 2017-05-29 11:26
As long as there is a deprecated warning, not error, for the old attribute for a few months. I think that a sudden breaking change must be avoided at all costs. In my case, it would add to the maintenance cost of my project and I couldn't explain this to my client.

Personally I didn't find find the old name confusing at all. It did exactly what it said it would do.

**Comment by n00bje** [comment] 2017-05-29 11:28
Unless I'm misunderstanding, the issue some people are having isn't the [ImplementPropertyChanged] attribute. Their issue is that they want to implement INotifyPropertyChanged without Fody weaving in the call to OnPropertyChanged, unless they explicitly tell Fody to do so. That way that can decide if legacy code needs weaving or not.

**Comment by SimonCropp** [comment] 2017-05-29 11:30
>  That way that can decide if legacy code needs weaving or not.

and they can achieve that by opting out with an  `[DoNotNotify]` on each legacy class

**Comment by n00bje** [comment] 2017-05-29 11:33
Which is fine by me. It says right on the front page what Fody does:
> NOTE: All classes that have INotifyPropertyChanged will have notification code injected into property sets.

In my opinion, this is just a case of RTFM.

**Comment by zspitz** [comment] 2017-05-29 12:34
@n00bje 

> It says right on the front page what Fody does:

To be fair, this warning was only added two days ago.

**Comment by SimonCropp** [comment] 2017-05-29 12:36
@zspitz it has been there for ages. it was last updated two days ago. the previous warning was 

> NOTE: All classes that do not have [ImplementPropertyChanged] but still have INotifyPropertyChanged will have notification code injected into property sets.

**Comment by SimonCropp** [comment] 2017-05-29 12:37
and that was added 2 years ago https://github.com/Fody/PropertyChanged/commit/8d0959d490dcb7c9b795bc30d4719b15c170b19b

**Comment by zspitz** [comment] 2017-05-29 12:39
@SimonCropp Yes; you\re right. I don't see how I missed that.

**Comment by buzzware** [comment] 2017-05-29 12:41
The current name perfectly describes what many of us want from this library, just that that isn't exactly what it was doing. 

It turns out this library provides 2 things :

A) implements property changed events for all properties of all classes that implement INotifyPropertyChanged
B) provides a convenience attribute for  implementing INotifyPropertyChanged (which in effect fires property changed events because of A)

In general, explicit is better than implicit. I'd be in favour of
1) I think the scope is currently assembly-wide, so  an assembly attribute eg [ImplementINotifyPropertyChangedEvents] being required on the assembly to get A for the whole assembly.
2) A [ImplementPropertyChangedEvents] class attribute doing A and B on the class regardless of the assembly level [ImplementINotifyPropertyChangedEvents]

This would mean :
1) those of us misunderstanding the old attribute would just have to search and replace [ImplementINotifyPropertyChanged] => [ImplementINotifyPropertyChangedEvents]
2) those wanting the intended behaviour would just have to add [ImplementINotifyPropertyChangedEvents] to the assembly
3) there would be no unexpected implicit magic for anyone

**Comment by zspitz** [comment] 2017-05-29 12:45
@buzzware 

> A) implements property changed events for all properties of all classes that implement INotifyPropertyChanged

Probably better to avoid the confusion engendered by _implements_ in this context; rather say _raises events on classes that implement INPC_.

**Comment by SimonCropp** [comment] 2017-05-29 12:49
@buzzware yes a few people have requested that. but whenever i drill into the actual use case there is none other than "i dont trust it". 

In properly designed models there should be no unnecessary side effects of notifying for a few extra types/properties. and given if explicit `OnPropertyChanged`  is detected in a property set then no modification is made then for classes with explicit notification there should be no side effects.

and again you can achieve an opt in model by adding one line of  `[DoNotNotify]` per class, and gradually removing it as desired

**Comment by distantcam** [comment] 2017-05-29 12:53
Re: Explicit vs implicit, my problem there is using PropertyChanged is an explicit act. By choosing to use the tool you're choosing to have all properties of all classes that implement `INotifyPropertyChanged` have change logic added to them, unless you opt-out. To change this to also requiring an assembly level attribute to tell PropertyChanged.Fody _"do your work"_ feels redundant. I've installed the tool, it should just work.

**Comment by zspitz** [comment] 2017-05-29 12:56
@SimonCropp Can you take a look at #249 ? I've tried to emphasize that the plugin's primary focus is on raising the `PropertyChanged` event by calling `OnPropertyChanged`, as opposed to implementing INPC.

**Comment by buzzware** [comment] 2017-05-29 12:59
This tiny library shouldn't put caveats on the rest of the code being well implemented. Opting out always causes issues for future team members and future code that must be aware of this. I was only suggesting the assembly-wide attribute to satisfy those wanting an implicit experience.

@distantcam Above I said you would be able to only add  [RaisePropertyChangedEvents] to a class, no assembly wide method required.

**Comment by zspitz** [comment] 2017-05-29 13:00
@distantcam Your (correct) understanding of the tool is that it raises the PropertyChanged event. But many people look at the tool and say "Fody.PropertyChanged -> INotifyPropertyChanged -> implements INotifyPropertyChanged". If the tool was called "RaisePropertyChanged", or "BroadcastPropertyChanged", I think there would be less room for confusion.

**Comment by distantcam** [comment] 2017-05-29 13:02
@zspitz That's why I like your idea of splitting out the part that implements INPC with the part that adds change logic to each property. That way there might be less confusion.

**Comment by SimonCropp** [comment] 2017-05-29 13:10
@buzzware 

> . Opting out always causes issues for future team members and future code that must be aware of this. 

Future team members should be aware of the tooling a projects uses and the ramifications.  assuming an opt in model completely covers that will lead to problems

**Comment by virzak** [comment] 2017-05-29 15:09
@SimonCropp Looks like there is no consensus on the best way to implement this.

In the meantime, could you please bring back the attribute so that not to cause the breaking change?
Thank you.

**Comment by 0x53A** [comment] 2017-05-29 16:52
There is already a way to move from opt-out to opt-in:

```C#
[assembly: PropertyChanged.FilterType("My.Specific.OptIn.Namespace.")]
```

I use this successfully in a legacy project to scope the rewriting to only one namespace.

**Comment by 0x53A** [comment] 2017-05-29 17:42
I propose to add two new Attributes: ``OptIn`` and ``OptOut``.

These can be applied at the assembly / class level.

The default is `` [assembly: OptIn] ``

So if I want to only weave one specific namespace I can add

```C#
[assembly: OptOut]
[assembly: OptIn("MyNamespace.")]
```

On the other hand, if I want to exclude only a few specific classes, I can either OptOut of one namespace, or add the attributes to these classes directly.

Class-Level attributes override assembly-level attributes, so I can add 

```C#

[assembly: OptOut]

[OptIn]
class MyClass { ... }

```

__(There are probably better names than OptIn / OptOut, these are just for demonstration).__

These Attributes control how classes which already implement ``INotifyPropertyChanged`` are handled.
I would prefer also add a new Attribute, maybe ``AddINotifyPropertyChanged`` which restores the behavior of ``ImplementPropertyChangedAttribute``, but is better named.

Adding ``AddINotifyPropertyChanged`` to a class that is in an OptOut scope generates an Error at Weave time. This can be fixed by adjusting the OptOut scope or adding OptIn at the class level.

Following, I would deprecate ``ImplementPropertyChangedAttribute`` / ``FilterType`` / ``DoNotNotify`` with Level=Warning, so that old code still compiles, but users are pointed with a warning to the preferred new way.

**Comment by n00bje** [comment] 2017-05-29 18:46
@0x53A 

Instead of an assembly attribute, I propose an option in `FodyWeavers.xml` similar to these: [https://github.com/Fody/PropertyChanged/wiki/Options](url)

For example:
```
<?xml version="1.0" encoding="utf-8" ?>
<Weavers>
  <PropertyChanged WeavingMode='Explicit'/> <!-- default is Auto -->
</Weavers>
```

```
public class LegacyClass : INotifyPropertyChanged
{
	public bool SomeProperty { get; set; } // This will NOT call OnPropertyChanged()

	public event PropertyChangedEventHandler PropertyChanged;
}
```

```
[WeaveOnPropertyChangedCall] // name for demonstration purposes
public class LegacyClass : INotifyPropertyChanged
{
	public bool SomeProperty { get; set; } // This WILL call OnPropertyChanged()

	public event PropertyChangedEventHandler PropertyChanged;
}
```

The default behavior would be the old behavior:
```
[ImplementPropertyChanged]
public class myPoco
{
	public bool SomeProperty { get; set; } // This will call OnPropertyChanged()
}
```

**Comment by virzak** [comment] 2017-05-31 14:01
@SimonCropp 
One more crazy thing that happened.
After upgrading to the latest version and realizing the breaking change, I went back to the previous version.

The compilation was fine, but the assembly was built without INPC. I cleaned the .nuget folder of Fody, but that didn't help. I was thinking for half a day that my system got screwed somehow, because it was working on all other machines.

After trying to upgrade and downgrade on other machines turned out it that this was a one way upgrade.

Could you please resolve this ASAP??? I mean, you don't want people reinstalling VS or their OS because they think something is wrong with their compiler / computer.

**Comment by virzak** [comment] 2017-05-31 14:32
Ok, so this was resolved by removing nuget folder of PropertyChanged.Fody

Apparently, no matter which version the project was using, it was always weaving using the last version available.

**Comment by SimonCropp** [comment] 2017-05-31 21:43
@virzak yeah that is a qwerk that is fixed when u move to the new csproj VS 2017 format. sorry but i dont think there is a way to fix that in the older csproj format.

**Comment by SimonCropp** [comment] 2017-05-31 21:44
everyone. I will bring back the attribute. but as i maintain this in my free time it is unlikely to happen until the weekend. sorry for the delay

**Comment by virzak** [comment] 2017-05-31 21:46
Thank you so much for this. Especially for doing this in your free time.

**Comment by virzak** [comment] 2017-06-01 01:05
@SimonCropp BTW, I am using the new VS 2017 csproj. The nuget folder I was talking about was global (C:\Users\virzak\.nuget\packages\propertychanged.fody).
This means that you upgrade ANY of your projects to latest PropertyChanged.Fody, it will cause a runtime error in all others. I just tried that and got an error.

Pretty scary...

**Comment by SimonCropp** [comment] 2017-06-01 01:07
@virzak r u using project.json?

**Comment by virzak** [comment] 2017-06-01 01:09
@SimonCropp No, PackageReference.

**Comment by SimonCropp** [comment] 2017-06-01 01:11
the problem you describe should not occur with PackageReference. we explicitly use the package passed in by msbuild https://github.com/Fody/Fody/blob/master/NuGet/Fody.targets#L64  if u think that is not working correctly i suggest raising an issue in https://github.com/Fody

**Closed** 2017-06-03 00:12 UTC

**Comment by SimonCropp** [comment] 2017-06-03 00:25
re added as `AddINotifyPropertyChangedInterfaceAttribute` 

and documented with 

> Raising an issue about "this attribute does not behave as expected" will result in a RTFM and the issue being closed.

**Comment by SimonCropp** [comment] 2017-06-03 00:27
deployed.

**Comment by SimonCropp** [comment] 2017-06-03 11:05
To all the people who weighed in here. Moving forward I would appreciate if you all had more of a voice on this project. Subscribe to notification, help triage other people's issues, help fix bugs. Etc. basically if u want to get value out of the project then help keep it alive.

Tbh when I get abused for the lib acting by design and as documented I wonder if it is worth supporting at all.

**Comment by aesalazar** [comment] 2017-07-05 19:47
@SimonCropp I know I am a bit late to the party here being that I am just getting around to updating the package and noticing the change but I wanted to say that I very much appreciate your efforts.  I am always amazed at how people can complain (very angrily no less) about something they did not pay anything for :).

**Comment by praschl** [comment] 2017-11-10 21:51
Thanks for bringing this back before I even used Fody, I love this attribute, and the whole project.
