### ISSUE TITLE
Compilation issue with source generator

### ISSUE THREAD

**Issue by virzak** [Fody/PropertyChanged#882] opened 2022-09-06 20:13 UTC
#### Describe the issue

Source generator version doesn't compile when a base class is used

The error is:

```
1>MSBUILD : error : Fody: The type 'FodySourceGenerator.ShouldHaveSourceGeneratedINPC' already implements INotifyPropertyChanged so [AddINotifyPropertyChangedInterfaceAttribute] is redundant.
```

Works fine if the base class also has `[AddINotifyPropertyChangedInterface]`, but the previous version didn't require it.

#### Minimal Repro

```cs
using FodySourceGenerator;
using PropertyChanged;

var zz = new ShouldHaveSourceGeneratedINPC();

namespace FodySourceGenerator
{

    [AddINotifyPropertyChangedInterface]
    public partial class ShouldHaveSourceGeneratedINPC : SomeBaseClass
    {
    }

    public class SomeBaseClass
    {
    }
}
```

**Comment by ltrzesniewski** [comment] 2022-09-07 17:58
Well, oops. 😨 

That's quite an oversight. We haven't considered the interaction between the source generator and the weaver.

I'll suggest a fix for this, but there may be other issues like this one.

**Comment by ltrzesniewski** [comment] 2022-09-07 19:08
Fix submitted, but...

I'm puzzled by the fact that the following code doesn't raise an error:

```C#
[AddINotifyPropertyChangedInterface]
public class Foo : INotifyPropertyChanged
{
    public event PropertyChangedEventHandler PropertyChanged;
}
```

The _"already implements INotifyPropertyChanged"_ error is raised only if `Foo` has a base class, like in the code in the OP. Is this the intended behavior @SimonCropp?

This is due to the following logic:

https://github.com/Fody/PropertyChanged/blob/902f31df32fcf34cdc92cfeea09988047f31197e/PropertyChanged.Fody/TypeNodeBuilder.cs#L33-L38

**Comment by tom-englert** [comment] 2022-09-08 08:17
IMO this is a weird edge case. I'm not sure if we should really put so much effort to support this. If you need such strange constructs you can disable the source generator or better avoid using the attribute at all.

**Comment by tom-englert** [comment] 2022-09-08 08:27
Or maybe we should just stop supporting the `AddINotifyPropertyChangedInterface` for the source generator?

**Comment by virzak** [comment] 2022-09-08 09:40
No, you should not introduce such a massive breaking change IMO.

**Comment by ltrzesniewski** [comment] 2022-09-08 10:33
We could also remove the error on a redundant `[AddINotifyPropertyChangedInterface]`. I don't think this check is really necessary, though I may be missing an edge case where it could be important. Currently it seems a bit broken to me (see my previous comment).

Ignoring the error if it's caused by generated code isn't really a big effort though, and seems safe.

In eiter case, I'd add the `[GeneratedCode]`/`[DebuggerNonUserCode]` to the source generator either way, since it makes the generated code consistent with what the weaver does.

**Comment by tom-englert** [comment] 2022-09-08 18:00
> No, you should not introduce such a massive breaking change IMO. 

Only for the source generator, not the weaver of course

**Comment by ltrzesniewski** [comment] 2022-09-13 21:51
So, what do we do with this?

**Comment by tom-englert** [comment] 2022-09-14 07:45
Sorry, been on vacation, will check this the next days

**Comment by ltrzesniewski** [comment] 2022-09-14 08:31
Ok, no worries. I've released the other fix in the meantime.

**Closed** 2022-09-17 14:51 UTC
Labels: Bug

**Comment by softlion** [comment] 2024-01-17 13:26
I use 4.1.0 and stumbled on this issue while converting old code.

The issue was, not code generation occurs on the child class I made partial and inherited INotifyPropertyChanged. And there was no warning nor error.

I finally undestood, thanks to this issue, that the parent class was decorated with AddInotifyPropertyChanged. When I converted it too, it worked.
