### ISSUE TITLE
Not working with latest version of Xamarin Forms

### ISSUE THREAD

**Issue by julesx** [Fody/PropertyChanged#286] opened 2017-10-10 17:29 UTC
in my output pane, i see the following at app startup

`2017-10-10 13:27:37.157 MyApp.iOS[1801:23810] Could not find `PropertyChanged` referenced by assembly `Mobile.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null`.`

INPC is not being triggered

**Comment by SimonCropp** [comment] 2017-10-10 21:38
Upload a repro

**Comment by Tom-92** [comment] 2017-10-11 15:40
For me its not working too, but ive no error messages in debug.
Xamarin.Forms Version 2.4.0.282
Fody Version 2.1.3
PropertyChanged.Fody Version 2.1.4

**Comment by SimonCropp** [comment] 2017-10-11 19:29
A repro doesnt mean your production code base. I means you go to the effort of finding just the moving peices need to reproduce the problem and upload that in a solution

**Comment by julesx** [comment] 2017-10-12 15:00
looks like PropertyChanged works with Fody 2.0.0 but not with 2.0.13

`Install-Package PropertyChanged.Fody` installs Fody 2.0.0 dependency and works
`Update-Package` updates Fody to 2.0.13 which then breaks PropertyChanged

repo: https://github.com/julesx/FodyTest

**Comment by Tom-92** [comment] 2017-10-12 15:12
@julesx nice! Your message would have been nice one hour before :D 
Because I have now extra created a repo to test with the buggy version.
So here is the test solution (created with all the latest versions of VS2017, Xamarin etc.)
[https://mega.nz/#!EXgC3BZJ!Pe6eWg62d13S5vOeECTfWTgid-ycm9fSHNx4s4Zr27c](url)

**Comment by lhughey** [comment] 2017-10-18 17:59
I'm can  also verify that its not working.  I downgraded to 2.1.2 and all seems good.

**Comment by MatthewTheRaven** [comment] 2017-10-18 19:50
I had this same issue. Oddly, removing PropertyChanged.Fody and Fody from my Project's packages and then adding them back in made it all work again.

**Comment by laurienicholas** [comment] 2017-10-26 08:25
This seems to be fixed with version 2.2.0 of Fody

**Closed** 2017-12-03 04:10 UTC
