### ISSUE TITLE
Not working with F#

### ISSUE THREAD

**Issue by mamcx** [Fody/PropertyChanged#280] opened 2017-09-06 21:40 UTC
I add the recent version I implement a class like:

    type DeudaRow() = 
        let event = new Event<_,_>()
        interface INotifyPropertyChanged with
            [<CLIEvent>]
            member x.PropertyChanged = event.Publish
     
        member x.OnPropertyChanged(name)=
             event.Trigger(x, new PropertyChangedEventArgs(name))

        member val valor = None with get,set

        member this.setRow(row:Deuda.DeudaClienteRecord) =
            this.valor <- Some(row.valor)

And also:

    [<AddINotifyPropertyChangedInterface>]
    type DeudaRow() = 
        member val valor = None with get,set

        member this.setRow(row:Deuda.DeudaClienteRecord) =
            this.valor <- Some(row.valor)

And the values are not update when I call "setRow". However done it manually:

    type ViewModelBase() =
        let propertyChanging = new Event<PropertyChangingEventHandler, PropertyChangingEventArgs>()
        let propertyChanged  = new Event<PropertyChangedEventHandler,  PropertyChangedEventArgs>()

        interface INotifyPropertyChanged with
            [<CLIEvent>]
            member self.PropertyChanged = propertyChanged.Publish
        
        member self.PropertyChanging = propertyChanging.Publish

        member self.OnPropertyChanging name =
            propertyChanging.Trigger(self, new PropertyChangingEventArgs(name))

        member self.OnPropertyChanged name =
            propertyChanged.Trigger(self, new PropertyChangedEventArgs(name))

    type DeudaRow() = 
        inherit ViewModelBase()

        member val valor = None with get,set
        member this.setRow(row:Deuda.DeudaClienteRecord) =
            this.valor <- Some(row.valor)
            base.OnPropertyChanged "valor"

And it work.

**Comment by SimonCropp** [comment] 2017-09-25 01:17
Given i dont actively use f# is there any chance of getting a PR for this?

**Comment by cmeeren** [comment] 2017-11-14 09:14
Perhaps this can shed more light on the problem. Consider the following class:

```f#
[<AddINotifyPropertyChangedInterface>]
type MyVm() =

  member val Str1 = "" with get, set
  member val Str2 = "" with get, set

  member this.Computed1 = 
    this.Str1 + this.Str2
  
  member this.Computed2 = 
    [this.Str1]
    |> List.map (fun str -> str + this.Str2)
    |> List.head

  member this.Computed3 = 
    this.Str2 |> ignore
    [this.Str1]
    |> List.map (fun str -> str + this.Str2)
    |> List.head
```

We have two settable properties, `Str1` and `Str2`, and three computed properties which do exactly the same thing (joins `Str1` and `Str2`) but using different methods.

`Computed1` simply concatenates the strings, and Fody.PropertyChanged works fine here. Setting either `Str1` or `Str2` triggers `Computed1`.

`Computed2` wraps `Str1` in a list, transforms the list by passing a function to `List.map` (akin to LINQ's `Select`) that closes over `Str2` and adds it to each element, and extracts the first element from the list. `Computed2` is triggered when `Str1` is changed, but *not* when `Str2` is changed.

`Computed3` is the same as `Computed2`, with the addition of passing `Str2` to the built-in `ignore` function just to have `Str2` be present directly in the scope of `Computed3` instead of in a deeper nested closure. `Computed3` is triggered correctly for both `Str1` and `Str2`. Thankfully this workaround seems to work even when "Optimize code" is checked (at least for the profile-based PCL I tested with).

Considering this, it would also be interesting to see whether Fody.PropertyChanged works correctly in C# when using LINQ and closing over a source property in a lambda.

**Comment by cmeeren** [comment] 2017-11-14 09:35
Regarding my previous LINQ comment; I tested with the following C# class, and **both properties work correctly**.

```f#
[AddINotifyPropertyChangedInterface]
public class TestVm
{
    public string Str1 { get; set; } = "";

    public string Str2 { get; set; } = "";

    public string Computed1 => this.Str1 + this.Str2;

    public string Computed2 =>
        new[] { this.Str1 }.Select(s => s + this.Str2).First();
}
```

**Comment by cmeeren** [comment] 2017-11-14 10:01
To fix this, it might be helpful to look at what the F# actually compiles to. Courtesy of SharpLab.io, here's [f# decompiled to C#](https://sharplab.io/#v2:DYLgZgzgNAJiDUAfALgTwA4FMAEBZVAagLYAUAlNgLwCwAUHdtkZkQEaYBO2AbgIbDYAysg4BGKtgBEk7AHcAlsgAW2AOaZkUbBA0MmLdlz4DhHAEwTpcxSvWbtu+rUbM2nbMvkQAdAGEA9kToAK7ImDDilNh6jJ4+puLwHkpe3qZmenquhsmpAUGh4RZRMdgA2nFpIqIAuqWIAHzYADJeyN5EvOjYJGDBAHbaItgAtE0Qw0mV6WT1Ta0T3kqYvDB0WQbulfkhYTAAzBKl0yIWjdjyqv3+HJilFSnx1XXOjNjnC+2d3b0DQ1xjf7YKaPKrmWavRgfNpLFYwIA===). Compare to [C# decompiled to C#](https://sharplab.io/#v2:CYLg1APgAgDABFAjAOgDIEsB2BHA3AWACgioBmBAJjgBUBTAZwBcA1AWyIG8i4eFyl4AZUYAnRHA5wA5rUa449WfIC+cALxwARJoLFCvPgkRDRVSTLkKlcVRu26iASDJH4AYQD2rAA4BXRrTA4moAfHDCYnBg4aYO+rwuAnCePv6BVKHcBryYtADuANoAuhJwjAAW6PTIEeLKNbQANrQAxowAFPTqYV3RFVU1pgCUyABi6CJM7UO6ykA). I know very little about these matters, but I notice that in the C# version, `Computed2` uses a compiler-generated method `get_Computed2` in which `Str2` is used directly, whereas in the F# version, `Computed2` instead uses a compiler-generated *internal class* `get_Computed2` where `Str2` the original `MyVm` is a member and its `Str2` is accessed in the method `get_Computed2.Invoke`.

**Comment by SimonCropp** [comment] 2017-11-19 22:39
i would appreciate a PR that adds a failing test. or at least a small sln that repos the issue

**Comment by cmeeren** [comment] 2017-11-20 22:26
Here's a minimal repro solution:

[Test.zip](https://github.com/Fody/PropertyChanged/files/1489315/Test.zip)

It consists of an F# library with this code:

```f#
namespace Test

open PropertyChanged

[<AddINotifyPropertyChangedInterface>]
type Test() = 
    
  member val Number = 0 with get, set

  member this.Works = 
    this.Number * 2

  member this.DoesNotWork =
    // Uncomment below to make it work
    //this.Number |> ignore
    [0..100] |> List.filter (fun c -> c > this.Number)
```

And a C# console app with this code:

```c#
using System;
using System.ComponentModel;

namespace ConsoleApp1
{
    using Test;

    class Program
    {
        static void Main(string[] args)
        {
            var test = new Test();
            test.PropertyChanged += OnPropertyChanged;
            test.Number = 42;
            Console.ReadKey();
        }

        private static void OnPropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            Console.WriteLine(e.PropertyName);
        }
    }
}
```

When this is run, the output is

```
Works
Number
```

The expected result is that `DoesNotWork ` is printed in addition to the two above.

Below is the F# code decompiled to C# ([link](https://sharplab.io/#v2:DYLgZgzgNAJiDUAfALgTwA4FMAEAVTEyAFAJTYC82AsAFDb3V3YC2mzARpgE7YBuAhsGwA5AK4duFbAAZsAdwCWyABbYA5pmRRsETbVr1WEnioUQAdAHUA9lwDWEKQYamLY49gBU2AEz6mRpwmymbmACLWBMLWyDb2FM70APRJ2ACqAHYAxtbMrBnI2JzA1nLYyNYs/HY4SvK2donYKa7m7kHYiAB82ApqGbaYTQDa0ubmAIzS0gC6nT0AMmbI5mAKwMiSRGCiGdhZ2AC0PQc9re3cJLRAA=)). As you can see, the `DoesNotWork` property getter is compiled as a separate class. You can visit the link and try un-commenting the commented line, which only changes a single line in the output (it adds `int number@ = this.Number@;` to the `Test.DoesNotWork` getter, and thus makes PropertyChanged.Fody work.

<details>
<summary>
Click to expand
</summary>

```c#
using Microsoft.FSharp.Collections;
using Microsoft.FSharp.Core;
using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyVersion("0.0.0.0")]
[assembly: FSharpInterfaceDataVersion(2, 0, 0)]
[CompilationMapping(SourceConstructFlags.Module)]
public static class _
{
    [CompilationMapping(SourceConstructFlags.ObjectType)]
    [Serializable]
    public class Test
    {
        internal int Number@;

        public int Number
        {
            get
            {
                return this.Number@;
            }
            set
            {
                this.Number@ = value;
            }
        }

        public int Works
        {
            get
            {
                return this.Number@ * 2;
            }
        }

        public FSharpList<int> DoesNotWork
        {
            get
            {
                return ListModule.Filter<int>(new _.get_DoesNotWork@11-1(this), SeqModule.ToList<int>(Operators.CreateSequence<int>(Operators.OperatorIntrinsics.RangeInt32(0, 1, 100))));
            }
        }

        public Test() : this()
        {
            this.Number@ = 0;
        }
    }

    [Serializable]
    internal sealed class get_DoesNotWork@11-1 : FSharpFunc<int, bool>
    {
        public _.Test @this;

        [DebuggerNonUserCode, CompilerGenerated]
        internal get_DoesNotWork@11-1(_.Test @this)
        {
            this.@this = @this;
        }

        public override bool Invoke(int c)
        {
            return c > this.@this.Number@;
        }
    }
}
namespace <StartupCode$_>
{
    internal static class $_
    {
    }
}
```

</details>

**Comment by TonyHenrique** [comment] 2017-11-29 16:56
I would like to use PropertyChanged.Fody on F# projects (.Net Standard 2.0)

    [<AddINotifyPropertyChangedInterface>]
    type Assunto = 
        {
            mutable Titulo : string
            mutable SetorId : Guid

            mutable TextoHTML: string
        }

**Comment by SimonCropp** [comment] 2017-11-30 02:30
can u please try with the latest version of fody

**Comment by cmeeren** [comment] 2017-12-02 13:52
@TonyHenrique That's not related to this issue, see #292 instead which is your exact problem.

**Comment by SimonCropp** [comment] 2017-12-03 07:34
@mamcx can u try v 2.2

**Comment by cmeeren** [comment] 2017-12-11 07:28
@SimonCropp What is the reason for closing? It's still not fixed as of 2.2.4, see the minimal repro solution I posted in https://github.com/Fody/PropertyChanged/issues/280#issuecomment-345852484.

**Comment by SimonCropp** [comment] 2017-12-11 08:29
@cmeeren sorry i mistakenly fixed this https://github.com/Fody/PropertyChanged/issues/280#issuecomment-347924838

so the problem is that propertychanged only deep scans the current type for dependencies. since f# compiles those functions into a diff type they are not detected. ie

```
namespace <StartupCode$Test>
{
	internal static class $Library1
	{
		[Serializable]
		internal sealed class get_DoesNotWork@16 : FSharpFunc<int, bool>
		{
			public Test @this;

			[DebuggerNonUserCode, CompilerGenerated]
			internal get_DoesNotWork@16(Test @this)
			{
				this.@this = @this;
			}

			public override bool Invoke(int c)
			{
				return c > this.@this.Number;
			}
		}
	}
}
```

happy to take a PR that fixes this

**Comment by cmeeren** [comment] 2017-12-11 12:49
Fody implementations/weaving is a bit above my level of understanding and not something I have the time to learn for the foreseeable future, so someone else will have to take a look at this. In the meantime, Stephen Cleary's [CalculatedProperties](https://github.com/StephenCleary/Mvvm.CalculatedProperties) works wonderfully.

**Comment by SimonCropp** [comment] 2018-02-20 23:40
if no one wants to fix this by submitting a PR i will mark f# as "not supported" and close this issue

**Comment by TonyHenrique** [comment] 2018-02-21 14:10
Fody is very nice.
F# not supported would be sad news.

**Comment by SimonCropp** [comment] 2018-04-04 13:47
closing this for now. if anyone wants to submit a PR it would be appreciated

**Closed by SimonCropp** 2018-04-04 13:47 UTC

**Comment by humhei** [comment] 2019-10-10 02:38
A workaround is define a ViewModelBase inherited from INotifyPropertyChanged in c#
```csharp
public abstract class ViewModelBase :  INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;
    }
```


Then in using it in f# world
```fsharp

type ViewModelTest() =
    inherit ViewModelBase()

    member val Hello = 6 with get, set

    member x.Yes = x.Hello + 1
```



The generated IL code is 
```csharp
using System;
using Microsoft.FSharp.Core;

namespace Shrimp.UI.Forms.FSharp
{
	// Token: 0x02000002 RID: 2
	[CompilationMapping(3)]
	[Serializable]
	public class ViewModelTest : ViewModelBase
	{
		// Token: 0x06000001 RID: 1 RVA: 0x00002050 File Offset: 0x00000250
		public ViewModelTest() : this()
		{
			this.Hello@ = 6;
		}

		// Token: 0x17000001 RID: 1
		// (get) Token: 0x06000002 RID: 2 RVA: 0x00002061 File Offset: 0x00000261
		// (set) Token: 0x06000003 RID: 3 RVA: 0x0000206C File Offset: 0x0000026C
		public int Hello
		{
			get
			{
				return this.Hello@;
			}
			set
			{
				if (this.Hello@ == value)
				{
					return;
				}
				this.Hello@ = value;
				this.<>OnPropertyChanged(<>PropertyChangedEventArgs.Yes);
				this.<>OnPropertyChanged(<>PropertyChangedEventArgs.Hello);
			}
		}

		// Token: 0x17000002 RID: 2
		// (get) Token: 0x06000004 RID: 4 RVA: 0x000020A4 File Offset: 0x000002A4
		public int Yes
		{
			get
			{
				return this.Hello + 1;
			}
		}

		// Token: 0x04000001 RID: 1
		internal int Hello@;
	}
}

```

**Comment by Brains** [comment] 2024-02-11 18:17
> A workaround is define a ViewModelBase inherited from INotifyPropertyChanged(implict interface implemention) in c#
>
> ```cs
> public abstract class ViewModelBase :  INotifyPropertyChanged
>     {
>         public event PropertyChangedEventHandler PropertyChanged;
>     }
> ```

@humhei Can you provide more details please?
Because I've created a separate C# project with the `ViewModelBase` as you described but it still did not work.

Tried:
- `netstandard2.0, net5.0, net6.0`
- with/without `Fody.PropertyChanged` installed on the C# project
- with/without `Caliburn.Micro.PropertyChangedBase` (implements `INotifyPropertyChanged`)
