### ISSUE TITLE
"Object reference not set to an instance of an object" error after upgrading to Window Anniversary

### ISSUE THREAD

**Issue by syaifulnizamyahya** [Fody/PropertyChanged#203] opened 2016-10-11 04:57 UTC
After upgrading my project to windows anniversary, compiling my project throws errors related to Fody PropertyChanged.

Changes that I made. 

http://i.stack.imgur.com/HXPGk.png

Errors that I received.

	Severity	Code	Description	Project	File	Line	Suppression State
	Error		Fody: An unhandled exception occurred:
	Exception:
	Object reference not set to an instance of an object.
	StackTrace:
	   at EqualityCheckWeaver.InjectEqualityCheck(Instruction targetInstruction, TypeReference targetType) in C:\projects\propertychanged\PropertyChanged.Fody\EqualityCheckWeaver.cs:line 92
	   at EqualityCheckWeaver.CheckAgainstField() in C:\projects\propertychanged\PropertyChanged.Fody\EqualityCheckWeaver.cs:line 39
	   at EqualityCheckWeaver.Execute() in C:\projects\propertychanged\PropertyChanged.Fody\EqualityCheckWeaver.cs:line 32
	   at ModuleWeaver.ProcessTypes(List`1 notifyNodes) in C:\projects\propertychanged\PropertyChanged.Fody\TypeProcessor.cs:line 38
	   at ModuleWeaver.Execute() in C:\projects\propertychanged\PropertyChanged.Fody\ModuleWeaver.cs:line 43
	   at lambda_method(Closure , Object )
	   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 161
	   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 82
	Source:
	PropertyChanged.Fody
	TargetSite:
	Void InjectEqualityCheck(Mono.Cecil.Cil.Instruction, Mono.Cecil.TypeReference)	Mast			

I go through the instructions here https://github.com/Fody/UniversalAppSample/ 

I have removed Fody, PropertyChanged and reinstall Fody and PropertyChanged 

Nothing works. 

What should I do?

**Comment by aline-almeida** [comment] 2016-10-11 14:47
Same thing here!

**Comment by distantcam** [comment] 2016-10-11 18:03
Duplicate of #200 

Downgrade to the previous version for now.

**Comment by syaifulnizamyahya** [comment] 2016-10-12 09:41
Downgraded to previous version. Still same error. Tried clean build, still the same. For now, i comment all [ImplementPropertyChanged] and uncomment one by one until I found the one that caused the error.

**Comment by aline-almeida** [comment] 2016-10-12 09:45
deleting the nuget packages folder and rebuilding worked for me.

**Comment by jlnostr** [comment] 2016-10-12 17:09
I'm now facing the same problem as @syaifulnizamyahya. After commenting out the `[ImplementPropertyChanged]` one by one, I found the problem class. You can look at it [here (sample project)](https://github.com/wallabag/windows-app/blob/master/src/wallabag/Models/Item.cs).

#200 is mentioning a crash on PCL, but apparently it's crashing on UWP as well.

**Closed** 2016-10-16 09:14 UTC
